#!/bin/sh
speed=4000
old_speed=$(uci get wshaper.settings.downlink)
if [ $# -eq 1 ] && [ "$1" == "-p" ]; then
  printf "$old_speed"
  exit 0
fi
printf "old speed cap was $old_speed\n"
if [ $# -gt 0 ]; then
  speed=$1
else
  exit 0
fi
printf "setting speed to $speed\n"

uci set wshaper.settings.downlink=$speed
uci commit
/etc/init.d/wshaper restart
